
import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import ClientOnly from "@/components/ClientOnly";
import Model from "@/components/Models/Model";
import RegisterModel from "@/components/Models/RegisterModel";
import ToastProvider from "@/components/ToastProvider";
import LoginModel from "@/components/Models/LoginModel";
import { getCurrentUser } from "@/action/getCurrentUser";
import { redirect, usePathname } from "next/navigation";
import RentModel from "@/components/Models/RentModel";
import SearchModel from "@/components/Models/SearchModel";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Nunito({
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser()
  // const path  = usePathname()
  // console.log(path)
  return (
    <html lang="en">
      <body className={font.className}>
        {/* {}
        {children} */}
        <ClientOnly >
          <SearchModel/>
          <RentModel/>
          <RegisterModel/>
          <LoginModel/>
          <ToastProvider/>
          <Navbar CurrentUser = {user}/>
        </ClientOnly>
        <div className="pb-20 pt-28">
        {children}
        </div>
      </body>
    </html>
  );
}



// 'use client'
// import { Space_Grotesk } from 'next/font/google'
// import {  usePathname } from 'next/navigation'

// const space_grotesk = Space_Grotesk({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-space-grotesk',
// })

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   const pathname = usePathname()
//   return (
//     <html className={`${space_grotesk.variable} scroll-smooth`} suppressHydrationWarning>
//       <link rel="manifest" href="/static/favicons/site.webmanifest" />
//       <link rel="mask-icon" href="/static/favicons/safari-pinned-tab.svg" color="#5bbad5" />
//       <meta name="theme-color" media="(prefers-color-scheme: light)" content="#fff" />
//       <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#000" />
//       <body className="bg-white pl-[calc(100vw-100%)] text-black antialiased dark:bg-gray-950 dark:text-white">
//         {(pathname == '/signin' || pathname == '/signup') ? (
//           <>{children}</>
//         ):( 
//           <section className="mx-auto max-w-3xl px-4 sm:px-6 xl:max-w-5xl xl:px-0">
//               <div className="flex h-screen flex-col justify-between font-sans">
//                 <main className="mb-auto">{children}</main>
//               </div>
//           </section>
//         ) }
//       </body>
//     </html>
//   )
// }